### ISSUE TITLE
countup dependency

### ISSUE THREAD

**Issue by mpascariu** [epicentre-msf/covid19#6]
Hi @PaulC91 

Nice app! Thanks for making it open source.
Could you please provide info about the `countup` package on which the dashboard is dependent. It does not seem to be a CRAN package. Where can we find it?

**Comment by PaulC91** [comment]
Hi Marius. Sure you can find it here: https://github.com/JohnCoene/countup. One of John Coene's many great packages!

**Comment by mpascariu** [comment]
Thanks Paul! Got it.

I am trying to reproduce it locally. Now, I run into this issue related to `addCustomLegend`:

```r
Listening on http://127.0.0.1:5266
Loading required namespace: shinydashboard
Warning: sf layer has inconsistent datum (+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs).
Need '+proj=longlat +datum=WGS84'
Warning: Error in : 'addCustomLegend' is not an exported object from 'namespace:leaflet'
  [No stack trace available]
Warning in min.default(numeric(0), na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
```

**Comment by PaulC91** [comment]
ah yes you need my own fork of leaflet for that:
```r
remotes::install_github("paulc91/leaflet")
```

**Comment by mpascariu** [comment]
thanks!
